# -*- coding: utf-8 -*-
"""Egypt_Real_Estate_Listings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eLwYqHYRi8qy9WXWcWgKj6NgO9rlX-f5
"""

import pandas as pd
import numpy as np

"""## Data Loading"""

df = pd.read_csv("egypt_real_estate_listings.csv")
df.head()

df.info()

df.describe()

df.shape

"""## Preprocessing"""

df['price'] = df['price'].astype(str).str.replace(',', '', regex=False)
df['price'] = pd.to_numeric(df['price'], errors='coerce')

df['price'].head()

df['down_payment'] = df['down_payment'].astype(str).str.replace('EGP', '', regex=False)
df['down_payment'] = df['down_payment'].str.replace(',', '', regex=False)
df['down_payment'] = pd.to_numeric(df['down_payment'], errors='coerce')
df['down_payment'].head()

print(df.isnull().sum())

df['bathrooms'] = df['bathrooms'].astype(str).str.extract('(\d+)').astype(float)
df['bathrooms'] = df['bathrooms'].fillna(df['bathrooms'].mean())
df['bathrooms'].head()
df['bathrooms'].mean()

df['bathrooms'].isnull().sum()

df['bedrooms'] = df['bedrooms'].astype(str).str.extract('(\d+)').astype(float)
df['bedrooms'] = df['bedrooms'].fillna(df['bedrooms'].mean())
df['bedrooms'].head()

df.dropna(subset = ['price'])

avg_price = df['price'].mean()
avg_price

"""## Expensive with respect to location"""

expensive = df.groupby('location')['price'].mean().sort_values(ascending=False)
expensive.head()

"""## Correlation between price and size"""

df['size'] = df['size'].astype(str).str.extract('(\\d{1,3}(?:,\\d{3})*(?:\\.\\d+)?)\\s*sqft').iloc[:, 0]
df['size'] = df['size'].str.replace(',', '', regex=False)
df['size'] = pd.to_numeric(df['size'], errors='coerce')
df['size'].head()

correlation = df['size'].corr(df['price'])
correlation

"""## How many bedrooms in most residencies"""

frequent_bedrooms = df['bedrooms'].value_counts(ascending=False)
frequent_bedrooms

"""## Most Frequent Residence Type"""

most_types = df['type'].value_counts(ascending=False)
most_types



"""## Handle Remaining Missing Values

### Subtask:
Drop rows with missing values in the 'price' column, as price is crucial for analysis. Then, display the updated count of missing values across all columns.

**Reasoning**:
First, I'll display the current count of missing values across all columns to provide a baseline before dropping any rows. This aligns with the first instruction.
"""

print("Missing values before dropping 'price' NaNs:")
print(df.isnull().sum())

"""**Reasoning**:
Now, I will remove rows where the 'price' column contains missing values, as it's a critical variable for further analysis.


"""

df.dropna(subset=['price'], inplace=True)
print("Missing values after dropping 'price' NaNs:")
print(df.isnull().sum())

"""## Summary:

### Data Analysis Key Findings
*   Initially, the 'price' column contained 539 missing values. The 'down\_payment' column had 14,479 missing values, 'available\_from' had 663, and 'payment\_method' had 541 missing values.
*   After dropping rows where the 'price' column had missing values, the 'price' column now has 0 missing values.
*   This operation also reduced missing values in other columns; for instance, missing values in 'down\_payment' decreased from 14,479 to 13,940, and 'available\_from' decreased from 663 to 548.
*   Despite the reduction, 'down\_payment' still has a high number of missing values (13,940), and 'description' and 'payment\_method' retain 1 and 2 missing values, respectively.

### Insights or Next Steps
*   The dataset is now suitable for analyses that depend on the 'price' column, as all missing price entries have been addressed.
*   Further strategies should be considered for handling the remaining significant missing values, particularly in the 'down\_payment' column, which could involve imputation or further investigation.

"""